import React from "react";

const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create Login Page",
        taskDescription: "Build responsive login page.",
        taskDate: "2026-06-05",
        category: "Frontend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Navbar Component",
        taskDescription: "Create reusable navbar.",
        taskDate: "2026-06-06",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Project Setup",
        taskDescription: "Initialize React project.",
        taskDate: "2026-06-01",
        category: "Setup",
      },
    ],
  },

  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Dashboard Design",
        taskDescription: "Design dashboard layout.",
        taskDate: "2026-06-07",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Sidebar Design",
        taskDescription: "Create responsive sidebar.",
        taskDate: "2026-06-08",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Logo Design",
        taskDescription: "Create application logo.",
        taskDate: "2026-06-02",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Landing Page",
        taskDescription: "Design landing page.",
        taskDate: "2026-06-03",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Color Scheme",
        taskDescription: "Finalize colors.",
        taskDate: "2026-06-04",
        category: "Design",
      },
    ],
  },

  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "API Integration",
        taskDescription: "Connect employee API.",
        taskDate: "2026-06-05",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Axios Setup",
        taskDescription: "Configure Axios.",
        taskDate: "2026-06-06",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Task API",
        taskDescription: "Create task endpoints.",
        taskDate: "2026-06-07",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "User API",
        taskDescription: "Create user endpoints.",
        taskDate: "2026-06-01",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Database Connection",
        taskDescription: "Connect MongoDB.",
        taskDate: "2026-06-02",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Email Service",
        taskDescription: "Implement notifications.",
        taskDate: "2026-06-03",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "JWT Auth",
        taskDescription: "Implement authentication.",
        taskDate: "2026-06-04",
        category: "Backend",
      },
    ],
  },

  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Testing Login",
        taskDescription: "Test login module.",
        taskDate: "2026-06-05",
        category: "Testing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Testing Dashboard",
        taskDescription: "Verify dashboard UI.",
        taskDate: "2026-06-06",
        category: "Testing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Cross Browser Test",
        taskDescription: "Test on browsers.",
        taskDate: "2026-06-07",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Bug Report #1",
        taskDescription: "Document issues.",
        taskDate: "2026-06-01",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Bug Report #2",
        taskDescription: "Document issues.",
        taskDate: "2026-06-02",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "UI Testing",
        taskDescription: "Check responsiveness.",
        taskDate: "2026-06-03",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Load Testing",
        taskDescription: "Check performance.",
        taskDate: "2026-06-04",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Regression Test",
        taskDescription: "Verify fixes.",
        taskDate: "2026-06-05",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Final QA",
        taskDescription: "Final review.",
        taskDate: "2026-06-06",
        category: "Testing",
      },
    ],
  },

  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Employee Module",
        taskDescription: "Build employee dashboard.",
        taskDate: "2026-06-05",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Task Module",
        taskDescription: "Build task section.",
        taskDate: "2026-06-06",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Admin Module",
        taskDescription: "Build admin panel.",
        taskDate: "2026-06-07",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Charts",
        taskDescription: "Add analytics charts.",
        taskDate: "2026-06-08",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Authentication",
        taskDescription: "Create login system.",
        taskDate: "2026-06-01",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Routing",
        taskDescription: "Setup React Router.",
        taskDate: "2026-06-02",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Header Component",
        taskDescription: "Create header.",
        taskDate: "2026-06-03",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Export Data",
        taskDescription: "Generate reports.",
        taskDate: "2026-06-04",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Search Feature",
        taskDescription: "Search employees.",
        taskDate: "2026-06-05",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Profile Page",
        taskDescription: "Create employee profile.",
        taskDate: "2026-06-06",
        category: "Development",
      },
    ],
  },
];

const admin = {
  id: 1,
  email: "admin@example.com",
  password: "123",
};

export const setLocalStorage = () => {};
export const getLocalStorage = () => {};